package main

import (
	"encoding/json"
	"fmt"
)

type AutoGenerated struct {
	Resultcode string `json:"resultcode"`
	Reason     string `json:"reason"`
	Result     struct {
		Province string `json:"province"`
		City     string `json:"city"`
		Areacode string `json:"areacode"`
		Zip      string `json:"zip"`
		Company  string `json:"company"`
		Card     string `json:"card"`
	} `json:"result"`
}

func main() {
	jsonStr := `{
			"resultcode": "200",
			"reason": "Return Successd!",
			"result": {
			"province": "浙江",
			"city": "杭州",
			"areacode": "0571",
			"zip": "310000",
			"company": "中国移动",
			"card": ""
			}
		}`

	var data AutoGenerated

	errr := json.Unmarshal([]byte(jsonStr), &data)

	if errr != nil {
		fmt.Println(errr)
	}
	fmt.Println(data.Result)

}
